name: build dist

on:
  push:
  pull_request:

jobs:
  build-dist:
    # note that you should usually specify versioned workflow file.
    uses: atsushieno/aap-lv2/.github/workflows/build-dist-app.yml@75f7907da27c22bf3b2b27f3dbced36feb55992d
